### ISSUE TITLE
When a Custom Exercise is deleted, it remains in the created Templates

### ISSUE THREAD

**Issue by reece346** [SCCapstone/Symphony#143]
When a custom exercise is deleted from the Custom Exercise page, it remains in the Templates it was apart of. For previous workouts, this may be necessary, but the tags and the description are removed from the Template whenever you click on  the exercise in the Template
![image](https://user-images.githubusercontent.com/77424091/231869366-072b642c-3266-4836-b9b5-d43d88560fc4.png)

**Comment by Esartawi** [comment]
not seeing this issue on my end. What emulator???
