### ISSUE TITLE
Testing Video

### ISSUE THREAD

**Issue by NikM3** [SCCapstone/Symphony#157]

**Comment by nicolekaate** [comment]
[https://user-images.githubusercontent.com/77560154/234128820-1f2932d9-fd7c-4859-8067-74f4ca7e6ec2.mp4](url)

**Comment by nicolekaate** [comment]
https://user-images.githubusercontent.com/77560154/234129034-b72af3da-7d94-477d-8336-d0eea13d06a0.mp4
